#######
#
# storymapjs-template
# basic template for self-hosted StoryMapJS
# https://github.com/thecdil/storymapjs-template
#
#######

#######
# SITE SETTINGS
#
title: Explore Quang Ngai
description: "Khám phá Quảng Ngãi"
year: 2025
author: Exp Quảng Ngãi .Org 
# add search box to navbar, true/false
search: true
# add representative image for social media sharing
# use a relative link to image file in project or full url
#featured-image:
#featured-image-alt:

##########
# URL VARIABLES [optional!]
#
# Optional if using GitHub Pages! If building manually, these must be set correctly.
#
# use url for the domain, e.g. https://thecdil.github.io
# on gh-pages follow the pattern: https://username.github.io
url: https://hoangphuctran93.github.io
# use baseurl to add subsection of the domain, e.g. /storymapjs-template
# on gh-pages this is a / followed by the name of the repository
# baseurl is your github repository's name prefixed with a /
baseurl: /storymapjs-template/
# location of code, the full url to your github repository
source-code: https://github.com/hoangphuctran93/storymapjs-template/


##########
# ROBOTS EXCLUDE [optional!]
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 


#######
# BUILD SETTINGS [usually leave as is]
#
# Defaults to simplify front matter,
# all files in the "pages" folder will be output at root of site
defaults:
  - scope:
      path: "pages"
    values:
      layout: page
      permalink: /:basename:output_ext

# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE]
