name: Sync NocoDB to StoryMaps

on:
  schedule:
    - cron: '0 */6 * * *'  # Chạy 4 lần mỗi ngày
  workflow_dispatch:  # Cho phép chạy thủ công

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Cần quyền ghi để push lên repository
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Lấy toàn bộ lịch sử để có thể push
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: pip install requests
        
      - name: Check environment variables
        run: |
          echo "Kiểm tra biến môi trường..."
          if [ -z "${{ secrets.NOCODB_DOMAIN }}" ]; then
            echo "NOCODB_DOMAIN không được thiết lập"
            exit 1
          fi
          if [ -z "${{ secrets.NOCODB_TOKEN }}" ]; then
            echo "NOCODB_TOKEN không được thiết lập"
            exit 1
          fi
          if [ -z "${{ secrets.NOCODB_TABLE_ID }}" ]; then
            echo "NOCODB_TABLE_ID không được thiết lập"
            exit 1
          fi
          echo "Domain: $(echo ${{ secrets.NOCODB_DOMAIN }} | sed -e 's|^https\?://||' -e 's|/.*$||')"
          echo "Table ID: Được thiết lập (không hiển thị vì bảo mật)"
          
      - name: Check network connectivity
        run: |
          echo "Kiểm tra kết nối đến domain..."
          ping -c 3 $(echo ${{ secrets.NOCODB_DOMAIN }} | sed -e 's|^https\?://||' -e 's|/.*$||') || echo "Ping không thành công nhưng tiếp tục workflow"
          
      - name: Run sync script
        env:
          NOCODB_DOMAIN: ${{ secrets.NOCODB_DOMAIN }}
          NOCODB_TOKEN: ${{ secrets.NOCODB_TOKEN }}
          NOCODB_TABLE_ID: ${{ secrets.NOCODB_TABLE_ID }}
          OUTPUT_DIR: "storymaps"
        run: python .github/scripts/sync_nocodb.py
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add storymaps/
          git status
          git diff --staged --quiet || git commit -m "Cập nhật dữ liệu StoryMapJS từ NocoDB"
          git push
